### ISSUE TITLE
livemap mod crashes on startup

### ISSUE THREAD

**Issue by destrofer** [ago1024/WurmClientModLauncher#8]
The issue is that it I can't start the modded game with livemap mod enabled. It shows the game window with load progress bar and then almost instantly crashes with this exception:
```
Unexpected crash while playing
org.gotti.wurmunlimited.modloader.classhooks.HookException: java.lang.NoSuchMethodError: com.wurmonline.client.resources.textures.ImageTextureLoader.loadNowrapNearestTexture(Ljava/awt/image/BufferedImage;)Lcom/wurmonline/client/resources/textures/ImageTexture;
	at org.gotti.wurmunlimited.modloader.classhooks.HookManager.invoke(HookManager.java:354)
	at com.wurmonline.client.renderer.gui.HeadsUpDisplay.init(HeadsUpDisplay.java)
	at com.wurmonline.client.WurmClientBase.runGame(WurmClientBase.java:279)
	at com.wurmonline.client.WurmClientBase.run(WurmClientBase.java:1612)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.wurmonline.client.resources.textures.ImageTextureLoader.loadNowrapNearestTexture(Ljava/awt/image/BufferedImage;)Lcom/wurmonline/client/resources/textures/ImageTexture;
	at com.wurmonline.client.renderer.gui.LiveMapWindow.createButton(LiveMapWindow.java:143)
	at com.wurmonline.client.renderer.gui.LiveMapWindow.<init>(LiveMapWindow.java:42)
	at org.gotti.wurmonline.clientmods.livehudmap.LiveHudMapMod$2.run(LiveHudMapMod.java:84)
	at org.gotti.wurmonline.clientmods.livehudmap.LiveHudMapMod.initLiveMap(LiveHudMapMod.java:100)
	at org.gotti.wurmonline.clientmods.livehudmap.LiveHudMapMod.access$000(LiveHudMapMod.java:28)
	at org.gotti.wurmonline.clientmods.livehudmap.LiveHudMapMod$1$1.invoke(LiveHudMapMod.java:64)
	at org.gotti.wurmunlimited.modloader.classhooks.HookManager.invoke(HookManager.java:344)
	... 4 more
```

**Comment by PapaPerks** [comment]
I have the same issue. running livemap 1.5.

**Comment by ago1024** [comment]
Theres a new release of livemap for WU 1.5: https://github.com/ago1024/LiveHudMap/releases/tag/v1.6

**Comment by destrofer** [comment]
Thanks and sorry, I didn't realize that I unpacked new client mod launcher over my old one and it didn't contain livemap mod by default, so I've got an old version. It works perfectly fine with the new version.
